spring:
  datasource:
    url: jdbc:postgresql://devdb.cgmkknqnw5hc.eu-west-1.rds.amazonaws.com:5432/
    username: postgres
    password: TqTjBw2yOYn80lzKypMR


jwt:
  token:
    secret: jwt_secret_key
    ttl_ms:
      access: 864_000_00
      refresh: 864_000_000


device:
  password: se1dkl4rfv3f4h7fgs98h2q96sjk


logging:
  config: ./logback.xml