spring:
  datasource:
    url: jdbc:postgresql://devdb.cgmkknqnw5hc.eu-west-1.rds.amazonaws.com:5432/
    username: postgres
    password: TqTjBw2yOYn80lzKypMR

tcp:
  port: 8080
  ip: localhost

jwt:
  token:
    secret: jwt_secret_key
    ttl_ms:
      access: 864_000_000
      refresh: 864_000_000


aes:
  key: verysecret

device:
  password: se1dkl4rfv3f4h7fgs98h2q96sjk

mail:
  username: authforagriguardian@gmail.com
  password: b+&%5NNY


code:
  lifetime: 3600000

logging:
  config: ./logback.xml